import { Poppins } from "next/font/google";
import "@/src/app/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./layout/header";
import { Toaster } from 'react-hot-toast';
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
